### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Iterny** [MSchmoecker/Valheim-Pressure-Plate#6]
Hello, is it possible to add for this mod localization support? I printed prefabs for your mod with other mod and tried to translate but it seems like it doesn't affect it, tried to put it in mod directory but nothing changes and it still using only english, Also would be great to have option to switch crafting category in hammer without additional mods. Or am I doing something wrong? i took english file from github, translated it and put in mod directory, or should i do proper way for it to work? I mean some pre-folders like Assets/Translations/langauge and put file there?

**Comment by MSchmoecker** [comment]
For localization, put the file under `Translations/{LanguageName}/translations.json` in the mod folder where PressurePlates.dll is located. The list of language names can be found here <https://valheim-modding.github.io/Jotunn/data/localization/language-list.html>. If you are happy with the translation, feel free to send the json so it can be directly included in the mod.

Changing the crafting category might come in a future Jotunn update, for now other mods like WackysDatabase or HammerTime are required.

**Comment by Iterny** [comment]
[Russian.json](https://github.com/user-attachments/files/16919369/Russian.json)
There it is then, now it works, thanks for instruction
